# Generated by Django 4.1.1 on 2022-09-15 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sep', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measured_in',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='measuredin',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
