# Generated by Django 4.1.1 on 2022-09-15 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sep', '0002_measured_in_product_measuredin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measured_in',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='measuredin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sep.measured_in'),
        ),
    ]
