# Generated by Django 4.1.1 on 2022-09-15 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sep', '0004_status_newsale_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsale',
            name='status',
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sep.status'),
        ),
    ]
