# Generated by Django 4.1.1 on 2022-09-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sep', '0005_remove_newsale_status_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='newdebt',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
